import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{marginTop: "2rem"}}>
        <h1 style={{display: "flex", justifyContent: "center"}}>
          Welcome to my Marvel app!
        </h1>
      </main>
    </div>
  )
}
