import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {

  const { user } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{marginTop: "2rem"}}>
        <h1 style={{display: "flex", justifyContent: "center"}}>
          Hello {user.attributes.given_name}!
        </h1>
        <h2 style={{display: "flex", justifyContent: "center"}}>Welcome to my NextJS app</h2>
      </main>
    </div>
  )
}
